import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{LayoutDashboard,ShoppingCart,Receipt,WalletCards,BarChart3,Settings,Search,Plus,RefreshCw,LogOut,Menu,TrendingUp,TrendingDown,Package,AlertTriangle}from'lucide-react';import{supabase}from'./lib/supabase';import{getDashboardData,getSales,getExpenses,getAccounts,createExpense,money,dateLabel}from'./lib/accounting';import'./styles.css';
const nav=[['dashboard','Dashboard',LayoutDashboard],['sales','Sales',ShoppingCart],['expenses','Expenses',Receipt],['accounts','Accounts',WalletCards],['reports','Reports',BarChart3],['settings','Settings',Settings]];
function Card({title,value,sub,icon:Icon,good}){return <div className="card kpi"><div className="kpiTop"><span>{title}</span><i><Icon size={17}/></i></div><strong>{value}</strong><small className={good?'good':''}>{sub}</small></div>}
function Login(){const[e,setE]=useState(''),[p,setP]=useState(''),[m,setM]=useState(''),[b,setB]=useState(false);async function go(x){x.preventDefault();setB(true);setM('');const{error}=await supabase.auth.signInWithPassword({email:e,password:p});if(error)setM(error.message);setB(false)}return <div className="login"><form className="loginCard" onSubmit={go}><div className="mark">E<span>&</span>C</div><h1>Exousia & Co.</h1><p>Accounting Portal</p><label>Email<input type="email" required value={e} onChange={x=>setE(x.target.value)}/></label><label>Password<input type="password" required value={p} onChange={x=>setP(x.target.value)}/></label>{m&&<div className="error">{m}</div>}<button className="primary wide" disabled={b}>{b?'Signing in…':'Sign in'}</button></form></div>}
function Shell({session}){const[page,setPage]=useState('dashboard'),[open,setOpen]=useState(false);return <div className="app"><aside className={open?'open':''}><div className="brand"><div className="mark small">E<span>&</span>C</div><div><b>Exousia & Co.</b><small>ACCOUNTING</small></div></div><nav>{nav.map(([id,t,I])=><button className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}} key={id}><I size={18}/>{t}</button>)}</nav><button className="signout" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/>Sign out</button></aside><main><header><button className="hamb" onClick={()=>setOpen(!open)}><Menu/></button><div><h2>{nav.find(x=>x[0]===page)[1]}</h2><small>{session.user.email}</small></div><span className="connected">● Connected</span></header><section className="content">{page==='dashboard'?<Dashboard/>:page==='sales'?<Sales/>:page==='expenses'?<Expenses/>:page==='accounts'?<Accounts/>:page==='reports'?<Reports/>:<SettingsPage/>}</section></main></div>}
function Loading({error,retry}){return <div className="card loading">{error?<><b>Could not load data</b><p>{error}</p><button className="secondary" onClick={retry}>Retry</button></>:<><RefreshCw className="spin"/><p>Loading…</p></>}</div>}
function Dashboard(){const[d,setD]=useState(),[e,setE]=useState('');const load=()=>getDashboardData().then(setD).catch(x=>setE(x.message));useEffect(()=>{load()},[]);if(!d)return <Loading error={e} retry={load}/>;return <><Title title="Business overview" sub="Your Exousia & Co. financial snapshot" action={<button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button>}/><div className="grid four"><Card title="Sales" value={money(d.sales)} sub={`${d.orders} orders`} icon={TrendingUp} good/><Card title="Expenses" value={money(d.expenses)} sub="Recorded expenses" icon={TrendingDown}/><Card title="Net profit" value={money(d.sales-d.expenses)} sub="Sales less expenses" icon={WalletCards} good={d.sales>=d.expenses}/><Card title="Inventory units" value={d.stock.toLocaleString()} sub={`${d.lowStock} low-stock items`} icon={Package}/></div><div className="grid two"><div className="card"><h3>Recent sales</h3><Mini rows={d.recentSales} sale/></div><div className="card"><h3>Recent expenses</h3><Mini rows={d.recentExpenses}/></div></div>{d.lowStock>0&&<div className="notice"><AlertTriangle size={18}/><div><b>Inventory attention</b><p>{d.lowStock} product(s) are at or below 5 units.</p></div></div>}</>}
function Title({title,sub,action}){return <div className="title"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Mini({rows,sale}){return <div className="mini">{rows.map(r=><div key={r.id}><span><b>{sale?(r.customer_name||r.customer?.name||'Customer'):(r.description||r.memo||'Expense')}</b><small>{dateLabel(r.created_at||r.expense_date)}</small></span><strong>{money(sale?(r.total??r.subtotal??0):r.amount)}</strong></div>)}{!rows.length&&<p className="empty">No records yet.</p>}</div>}
function Sales(){const[r,setR]=useState([]),[q,setQ]=useState(''),[e,setE]=useState('');const load=()=>getSales().then(setR).catch(x=>setE(x.message));useEffect(()=>{load()},[]);const f=r.filter(x=>`${x.id} ${x.customer_name||''} ${x.status||''}`.toLowerCase().includes(q.toLowerCase()));return <><Title title="Sales" sub="Live orders from the existing storefront" action={<button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button>}/><div className="search"><Search size={17}/><input placeholder="Search order, customer, status…" value={q} onChange={x=>setQ(x.target.value)}/></div>{e?<div className="error">{e}</div>:<Table headers={['Date','Order','Customer','Status','Payment','Total']} rows={f.map(x=>[dateLabel(x.created_at),String(x.id).slice(0,8)+'…',x.customer_name||x.customer?.name||x.customer?.email||'Customer',x.order_status||x.status||'pending',x.payment_status||'Pending',money(x.total??x.subtotal??0)])}/>}</>}
function Expenses(){const[r,setR]=useState([]),[e,setE]=useState(''),[show,setShow]=useState(false);const load=()=>getExpenses().then(setR).catch(x=>setE(x.message));useEffect(()=>{load()},[]);return <><Title title="Expenses" sub="Track operating costs and business spending" action={<button className="primary" onClick={()=>setShow(true)}><Plus size={17}/>Add expense</button>}/>{e?<div className="error">{e}</div>:<Table headers={['Date','Description','Category','Status','Amount']} rows={r.map(x=>[dateLabel(x.expense_date||x.created_at),x.description||x.memo||'—',x.category||x.expense_category||'General',x.status||'posted',money(x.amount)])}/>} {show&&<Expense onClose={()=>setShow(false)} onSaved={()=>{setShow(false);load()}}/>}</>}
function Expense({onClose,onSaved}){const[f,setF]=useState({description:'',amount:'',category:'General',expense_date:new Date().toISOString().slice(0,10)}),[b,setB]=useState(false);return <div className="back"><div className="modal"><div className="modalHead"><h3>New expense</h3><button onClick={onClose}>×</button></div><label>Description<input value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="grid two"><label>Amount (PHP)<input type="number" min="0" step=".01" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Date<input type="date" value={f.expense_date} onChange={e=>setF({...f,expense_date:e.target.value})}/></label></div><label>Category<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{['General','Supplies','Packaging','Shipping','Marketing','Utilities','Rent','Salaries','Equipment','Other'].map(x=><option key={x}>{x}</option>)}</select></label><div className="actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!f.amount||b} onClick={async()=>{setB(true);try{await createExpense({...f,amount:Number(f.amount)});onSaved()}finally{setB(false)}}}>{b?'Saving…':'Save expense'}</button></div></div></div>}
function Accounts(){const[r,setR]=useState([]),[e,setE]=useState('');useEffect(()=>{getAccounts().then(setR).catch(x=>setE(x.message))},[]);return <><Title title="Chart of accounts" sub="Accounts from the accounting schema"/>{e?<div className="error">{e}</div>:<Table headers={['Code','Account','Type','Normal balance','Status']} rows={r.map(x=>[x.code,x.name,x.account_type||x.type,x.normal_balance||'—',x.active===false?'Inactive':'Active'])}/>}</>}
function Reports(){const[d,setD]=useState();useEffect(()=>{getDashboardData().then(setD).catch(x=>console.error('Reports load error:',x))},[]);return <><Title title="Reports" sub="Management-level accounting reports"/><div className="grid three"><div className="card report"><BarChart3/><b>Profit & Loss</b><small>Revenue less expenses</small><strong>{d?money(d.sales-d.expenses):'—'}</strong></div><div className="card report"><ShoppingCart/><b>Sales report</b><small>Store orders</small><strong>{d?money(d.sales):'—'}</strong></div><div className="card report"><Package/><b>Inventory</b><small>Current units</small><strong>{d?d.stock.toLocaleString():'—'} units</strong></div></div><div className="card"><h3>Architecture</h3><p className="muted">This accounting portal is a separate application. It reads the same Supabase project as the storefront, without changing storefront code.</p></div></>}
function SettingsPage(){return <><Title title="Settings" sub="Accounting application settings"/><div className="card settings"><div><span>Supabase</span><b className="good">Connected</b></div><div><span>Application</span><b>Standalone Accounting</b></div><div><span>Storefront</span><b>Exousia & Co.</b></div><div><span>Currency</span><b>PHP (₱)</b></div></div></>}
function Table({headers,rows}){return <div className="card table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td className={j===r.length-1?'right':''} key={j}>{v}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={headers.length} className="empty">No records found.</td></tr>}</tbody></table></div>}

class ErrorBoundary extends React.Component {
  constructor(props) { super(props); this.state = { error: null }; }
  static getDerivedStateFromError(error) { return { error }; }
  componentDidCatch(error) { console.error("Accounting portal runtime error:", error); }
  render() {
    if (this.state.error) return <div className="loadingScreen"><div className="card" style={{maxWidth:720,margin:"24px"}}><b>Something went wrong</b><p>{this.state.error?.message || "Unexpected application error."}</p><button className="secondary" onClick={() => window.location.reload()}>Reload application</button></div></div>;
    return this.props.children;
  }
}

function App(){const[s,setS]=useState(null),[loading,setL]=useState(true);useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data,error})=>{if(!alive)return;if(error){console.error('Auth initialization error:',error);setS(null)}else setS(data.session);setL(false)}).catch(error=>{console.error('Auth initialization error:',error);if(alive){setS(null);setL(false)}});const{data:l}=supabase.auth.onAuthStateChange((_,x)=>setS(x));return()=>{alive=false;l.subscription.unsubscribe()}},[]);if(loading)return <div className="loadingScreen">Loading Exousia & Co. Accounting…</div>;return s?<Shell session={s}/>:<Login/>}createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
